spring.application.name: sample-spring-boot

management:
    endpoints.web.exposure.include: "*"
    tracing.sampling.probability: 1.0

logging.level:
    ROOT: DEBUG
    io.opentelemetry.exporter.internal.grpc: DEBUG



otel:
    global:
        enabled: true
    propagation.enabled: true
    propagators: b3,tracecontext
    autoconfigure:
        enabled: true
    exporters:
        otlp: true
    instrumentation:
        micrometer.enabled: true
        common.default-enabled: true
    sdk.enabled: true
    service.name: ${spring.application.name}
    metrics.exporter: none
    logs.exporter: none
    traces.exporter: otlp
    exporter.otlp:
        protocol: grpc
        endpoint: https://jaeger-grpc.apps.dhaka.cf-app.com
    resource.attributes.service.name: ${spring.application.name}
