spring.application.name: sample-spring-boot

management:
    endpoints.web.exposure.include: "*"
    tracing:
        enabled: true
        baggage.enabled: true
        propagation.type: [b3, b3_multi, w3c]
        sampling.probability: 1.0
    otlp.tracing:
        compression: none
        endpoint: https://jaeger-grpc.apps.dhaka.cf-app.com/v1/traces


logging.level:
    ROOT: DEBUG
    io.opentelemetry.exporter.internal.grpc: DEBUG


# otel:
#     sdk.disabled: false
#     resource.attributes:
#         service.name: ${spring.application.name}
#     log.level: DEBUG
#     traces.sampler: parentbased_always_on
#     bsp:
#         schedule.delay: 1000
#         export.timeout: 15000
#     traces.exporter: otlp
#     metrics.exporter: none
#     logs.exporter: none
#     exporter.otlp.traces:
#         endpoint: https://jaeger-grpc.apps.dhaka.cf-app.com
#         protocol: grpc
