spring.application.name: sample-spring-boot

management:
    endpoints.web.exposure.include: "*"
    tracing.sampling.probability: 1.0

logging.level:
    ROOT: DEBUG
    io.opentelemetry.exporter.internal.grpc: DEBUG


otel:
    sdk.enabled: true
    service.name: ${spring.application.name}
    traces:
        exporter: otlp
        sampler: alwaysonsampler
    exporter.otlp:
        protocol: grpc
        endpoint: https://jaeger-grpc.apps.dhaka.cf-app.com
    experimental.exporter.otlp.retry.enabled: true
    resource.attributes.service.name: ${spring.application.name}
